site_name: team-viseu
site_description: "Main documentation for team-viseu project"
repo_url: https://github.com/xgeeks-geekathon/team-viseu.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
